# -*- coding: utf-8 -*-
"""modelbuilding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPi_hzjzdRye0MNA7qg69OLkA5d4XHd0
"""

import pandas as pd

df = pd.read_csv('/content/Salary Data.csv')
display(df.head())

print(df)

print(df.duplicated())

df.isnull().sum()

"""### Handling Missing Values

I'll replace null values with the mean for numerical columns and the mode for categorical columns to ensure the dataset is complete for further analysis.
"""

# Impute numerical columns with the mean
for col in ['Age', 'Years of Experience', 'Salary']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

# Impute categorical columns with the mode
for col in ['Gender', 'Education Level', 'Job Title']:
    if df[col].isnull().any():
        # Use .iloc[0] to get the first mode in case of multiple modes
        df[col] = df[col].fillna(df[col].mode()[0])

display(df.isnull().sum())

"""### Identify and Handle Duplicate Rows

I will now identify and display any duplicate rows in the dataset and then remove them to ensure data uniqueness.
"""

duplicate_rows = df[df.duplicated()]
print(f"Number of duplicate rows: {len(duplicate_rows)}")
display(duplicate_rows.head())

df.drop_duplicates(inplace=True)
print(f"Number of rows after removing duplicates: {len(df)}")

"""### Label Encoding Categorical Features

I will now apply Label Encoding to convert categorical columns ('Gender', 'Education Level', 'Job Title') into numerical representations. This is a common preprocessing step for many machine learning algorithms.
"""

from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# List of categorical columns to encode
categorical_cols = ['Gender', 'Education Level', 'Job Title']

# Apply LabelEncoder to each categorical column
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

display(df.head())

"""### Separating Dependent and Independent Variables

I will now separate the dataset into independent variables (features, `X`) and the dependent variable (target, `y`). In this case, 'Salary' will be our dependent variable.
"""

# Separate features (X) and target (y)
X = df.drop('Salary', axis=1)
y = df['Salary']

print(f"Shape of X (features): {X.shape}")
print(f"Shape of y (target): {y.shape}")

display(X.head())
display(y.head())

"""### Splitting Data into Training and Testing Sets

I will now divide the dataset into training and testing sets to prepare for model building and evaluation. This ensures that the model is trained on one portion of the data and evaluated on unseen data to assess its generalization capability.
"""

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""### Model Building and Training

#### 1. Linear Regression

Linear Regression is a fundamental supervised learning algorithm used for predictive analysis. It models the relationship between a dependent variable and one or more independent variables by fitting a linear equation to the observed data. The goal is to find the best-fitting line (or hyperplane in higher dimensions) that minimizes the sum of squared residuals between the observed and predicted values.
"""

from sklearn.linear_model import LinearRegression

# Initialize and train the Linear Regression model
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_lin_reg = lin_reg_model.predict(X_test)

print("Linear Regression Model Trained and Predictions Made.")

"""#### 2. Decision Tree Regressor

A Decision Tree Regressor is a non-parametric supervised learning method used for regression tasks. It works by creating a tree-like model of decisions, where each internal node represents a 'test' on an attribute, each branch represents the outcome of the test, and each leaf node represents the final predicted value. The goal is to create a model that predicts the value of a target variable by learning simple decision rules inferred from the data features.
"""

from sklearn.tree import DecisionTreeRegressor

# Initialize and train the Decision Tree Regressor model
dtree_reg_model = DecisionTreeRegressor(random_state=42)
dtree_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_dtree_reg = dtree_reg_model.predict(X_test)

print("Decision Tree Regressor Model Trained and Predictions Made.")

"""#### 3. Random Forest Regressor

Random Forest Regressor is an ensemble learning method that operates by constructing a multitude of decision trees during training. For regression tasks, it outputs the mean or average prediction of the individual trees. It is known for its ability to handle complex datasets, reduce overfitting, and provide higher accuracy compared to single decision trees.
"""

from sklearn.ensemble import RandomForestRegressor

# Initialize and train the Random Forest Regressor model
rf_reg_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_rf_reg = rf_reg_model.predict(X_test)

print("Random Forest Regressor Model Trained and Predictions Made.")

"""#### 4. Support Vector Machine (SVM) Regressor

Support Vector Machine (SVM) Regressor, specifically Support Vector Regression (SVR), uses the same principles as SVM for classification but applies them to regression problems. Instead of trying to fit the maximum number of data points between a decision boundary, SVR tries to fit the best line within a threshold margin, aiming to minimize the error within that margin and penalizing errors outside it. This makes it robust to outliers and effective in high-dimensional spaces.
"""

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

# Scale the data for SVR (it's sensitive to feature scaling)
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).flatten()
X_test_scaled = scaler_X.transform(X_test)

# Initialize and train the SVR model
svr_model = SVR(kernel='rbf') # Radial Basis Function kernel is common for SVR
svr_model.fit(X_train_scaled, y_train_scaled)

# Make predictions and inverse transform to original scale
y_pred_svr_scaled = svr_model.predict(X_test_scaled)
y_pred_svr = scaler_y.inverse_transform(y_pred_svr_scaled.reshape(-1, 1)).flatten()

print("SVR Model Trained and Predictions Made.")

"""#### 5. K-Nearest Neighbors (KNN) Regressor

K-Nearest Neighbors (KNN) Regressor is a non-parametric, instance-based learning algorithm. It predicts the value of a new data point by finding the 'k' nearest data points (neighbors) in the training set and then taking the average of their target values. The 'distance' between data points is usually calculated using Euclidean distance or other metric.
"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize and train the KNN Regressor model
knn_reg_model = KNeighborsRegressor(n_neighbors=5) # n_neighbors is a key hyperparameter
knn_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_knn_reg = knn_reg_model.predict(X_test)

print("KNN Regressor Model Trained and Predictions Made.")

"""#### 4. Support Vector Machine (SVM) Regressor

Support Vector Machine (SVM) Regressor, specifically Support Vector Regression (SVR), uses the same principles as SVM for classification but applies them to regression problems. Instead of trying to fit the maximum number of data points between a decision boundary, SVR tries to fit the best line within a threshold margin, aiming to minimize the error within that margin and penalizing errors outside it. This makes it robust to outliers and effective in high-dimensional spaces.
"""

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

# Scale the data for SVR (it's sensitive to feature scaling)
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).flatten()
X_test_scaled = scaler_X.transform(X_test)

# Initialize and train the SVR model
svr_model = SVR(kernel='rbf') # Radial Basis Function kernel is common for SVR
svr_model.fit(X_train_scaled, y_train_scaled)

# Make predictions and inverse transform to original scale
y_pred_svr_scaled = svr_model.predict(X_test_scaled)
y_pred_svr = scaler_y.inverse_transform(y_pred_svr_scaled.reshape(-1, 1)).flatten()

print("SVR Model Trained and Predictions Made.")

"""#### 5. K-Nearest Neighbors (KNN) Regressor

K-Nearest Neighbors (KNN) Regressor is a non-parametric, instance-based learning algorithm. It predicts the value of a new data point by finding the 'k' nearest data points (neighbors) in the training set and then taking the average of their target values. The 'distance' between data points is usually calculated using Euclidean distance or other metric.
"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize and train the KNN Regressor model
knn_reg_model = KNeighborsRegressor(n_neighbors=5) # n_neighbors is a key hyperparameter
knn_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_knn_reg = knn_reg_model.predict(X_test)

print("KNN Regressor Model Trained and Predictions Made.")

"""### Model Evaluation"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate_model(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    print(f"--- {model_name} ---")
    print(f"Mean Absolute Error (MAE): {mae:.2f}")
    print(f"Mean Squared Error (MSE): {mse:.2f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
    print(f"R-squared (R2): {r2:.2f}")
    print("\n")

# Evaluate Linear Regression
evaluate_model(y_test, y_pred_lin_reg, "Linear Regression")

# Evaluate Decision Tree Regressor
evaluate_model(y_test, y_pred_dtree_reg, "Decision Tree Regressor")

# Evaluate Random Forest Regressor
evaluate_model(y_test, y_pred_rf_reg, "Random Forest Regressor")

# Evaluate SVR
evaluate_model(y_test, y_pred_svr, "Support Vector Regressor (SVR)")

# Evaluate KNN Regressor
evaluate_model(y_test, y_pred_knn_reg, "K-Nearest Neighbors (KNN) Regressor")

"""### Model Evaluation"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate_model(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    print(f"--- {model_name} ---")
    print(f"Mean Absolute Error (MAE): {mae:.2f}")
    print(f"Mean Squared Error (MSE): {mse:.2f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
    print(f"R-squared (R2): {r2:.2f}")
    print("\n")

# Evaluate Linear Regression
evaluate_model(y_test, y_pred_lin_reg, "Linear Regression")

# Evaluate Decision Tree Regressor
evaluate_model(y_test, y_pred_dtree_reg, "Decision Tree Regressor")

# Evaluate Random Forest Regressor
evaluate_model(y_test, y_pred_rf_reg, "Random Forest Regressor")

# Evaluate SVR
evaluate_model(y_test, y_pred_svr, "Support Vector Regressor (SVR)")

# Evaluate KNN Regressor
evaluate_model(y_test, y_pred_knn_reg, "K-Nearest Neighbors (KNN) Regressor")

"""### Model Evaluation"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate_model(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    print(f"--- {model_name} ---")
    print(f"Mean Absolute Error (MAE): {mae:.2f}")
    print(f"Mean Squared Error (MSE): {mse:.2f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
    print(f"R-squared (R2): {r2:.2f}")
    print("\n")

# Evaluate Linear Regression
evaluate_model(y_test, y_pred_lin_reg, "Linear Regression")

# Evaluate Decision Tree Regressor
evaluate_model(y_test, y_pred_dtree_reg, "Decision Tree Regressor")

# Evaluate Random Forest Regressor
evaluate_model(y_test, y_pred_rf_reg, "Random Forest Regressor")

# Evaluate SVR
evaluate_model(y_test, y_pred_svr, "Support Vector Regressor (SVR)")

# Evaluate KNN Regressor
evaluate_model(y_test, y_pred_knn_reg, "K-Nearest Neighbors (KNN) Regressor")

"""### Model Evaluation"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate_model(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    print(f"--- {model_name} ---")
    print(f"Mean Absolute Error (MAE): {mae:.2f}")
    print(f"Mean Squared Error (MSE): {mse:.2f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
    print(f"R-squared (R2): {r2:.2f}")
    print("\n")

# Evaluate Linear Regression
evaluate_model(y_test, y_pred_lin_reg, "Linear Regression")

# Evaluate Decision Tree Regressor
evaluate_model(y_test, y_pred_dtree_reg, "Decision Tree Regressor")

# Evaluate Random Forest Regressor
evaluate_model(y_test, y_pred_rf_reg, "Random Forest Regressor")

# Evaluate SVR
evaluate_model(y_test, y_pred_svr, "Support Vector Regressor (SVR)")

# Evaluate KNN Regressor
evaluate_model(y_test, y_pred_knn_reg, "K-Nearest Neighbors (KNN) Regressor")

"""### Model Visualization"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

def get_model_metrics(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    return {
        'Model': model_name,
        'MAE': mae,
        'MSE': mse,
        'RMSE': rmse,
        'R2 Score': r2
    }

# Collect metrics for all models
metrics = []
metrics.append(get_model_metrics(y_test, y_pred_lin_reg, "Linear Regression"))
metrics.append(get_model_metrics(y_test, y_pred_dtree_reg, "Decision Tree Regressor"))
metrics.append(get_model_metrics(y_test, y_pred_rf_reg, "Random Forest Regressor"))
metrics.append(get_model_metrics(y_test, y_pred_svr, "Support Vector Regressor (SVR)"))
metrics.append(get_model_metrics(y_test, y_pred_knn_reg, "K-Nearest Neighbors (KNN) Regressor"))

metrics_df = pd.DataFrame(metrics)
display(metrics_df)

fig, axes = plt.subplots(2, 2, figsize=(18, 12))
fig.suptitle('Comparison of Regression Model Performance', fontsize=20)

# MAE Plot
sns.barplot(ax=axes[0, 0], x='Model', y='MAE', data=metrics_df, palette='viridis')
axes[0, 0].set_title('Mean Absolute Error (MAE)', fontsize=14)
axes[0, 0].set_ylabel('MAE', fontsize=12)
axes[0, 0].set_xlabel('')
axes[0, 0].tick_params(axis='x', rotation=45)

# MSE Plot
sns.barplot(ax=axes[0, 1], x='Model', y='MSE', data=metrics_df, palette='magma')
axes[0, 1].set_title('Mean Squared Error (MSE)', fontsize=14)
axes[0, 1].set_ylabel('MSE', fontsize=12)
axes[0, 1].set_xlabel('')
axes[0, 1].tick_params(axis='x', rotation=45)

# RMSE Plot
sns.barplot(ax=axes[1, 0], x='Model', y='RMSE', data=metrics_df, palette='cividis')
axes[1, 0].set_title('Root Mean Squared Error (RMSE)', fontsize=14)
axes[1, 0].set_ylabel('RMSE', fontsize=12)
axes[1, 0].set_xlabel('')
axes[1, 0].tick_params(axis='x', rotation=45)

# R2 Score Plot
sns.barplot(ax=axes[1, 1], x='Model', y='R2 Score', data=metrics_df, palette='plasma')
axes[1, 1].set_title('R-squared (R2 Score)', fontsize=14)
axes[1, 1].set_ylabel('R2 Score', fontsize=12)
axes[1, 1].set_xlabel('')
axes[1, 1].tick_params(axis='x', rotation=45)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""### Saving the Best Model"""

import pickle

# Identify the best model (RandomForestRegressor based on previous analysis)
best_model = rf_reg_model

# Define the filename for the pickled model
model_filename = 'best_model.pkl'

# Save the best model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"The best model (RandomForestRegressor) has been saved as '{model_filename}'.")